'use client';
import {readServiceJSON} from '@/lib/service-response';
import {useEffect,useRef,useState} from 'react';
import type {Draft} from '@/lib/schema';
type Diagram=Draft['diagrams'][number];
let library:Promise<any>|undefined;
async function prepare(d:Diagram){const response=await fetch('/api/desmos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d.graph)});const data=await readServiceJSON(response,'Desmos configuration') as {key:string;expressions:{latex:string;color:string}[];error?:string};if(!response.ok)throw new Error(data.error||'Desmos could not load.');if(!library)library=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://www.desmos.com/api/v1.11/calculator.js?apiKey='+encodeURIComponent(data.key);script.onload=()=>resolve((window as any).Desmos);script.onerror=()=>{library=undefined;script.remove();reject(new Error('Desmos could not load. Check your connection.'));};document.head.appendChild(script);});return {Desmos:await library,expressions:data.expressions};}
function create(element:HTMLElement,d:Diagram,Desmos:any,expressions:any[]){const g=d.graph!;const calc=Desmos.GraphingCalculator(element,{expressions:false,settingsMenu:false,keypad:false,showGrid:false,xAxisArrowMode:Desmos.AxisArrowModes.POSITIVE,yAxisArrowMode:Desmos.AxisArrowModes.POSITIVE,xAxisLabel:g.x_label,yAxisLabel:g.y_label,xAxisNumbers:false,yAxisNumbers:false,pointsOfInterest:false,trace:false});calc.setMathBounds({left:g.x_min,right:g.x_max,bottom:g.y_min,top:g.y_max});calc.setExpressions([...expressions.map((e,i)=>({...e,id:'curve'+i})),...g.points.map((p,i)=>({id:'point'+i,latex:`(${p.x},${p.y})`,showLabel:!!p.label,label:p.label,color:'#14233b'}))]);return calc;}
export async function desmosPng(d:Diagram){const {Desmos,expressions}=await prepare(d);const el=document.createElement('div');Object.assign(el.style,{position:'fixed',left:'-10000px',width:'800px',height:'500px'});document.body.appendChild(el);let calc:any;try{calc=create(el,d,Desmos,expressions);const url=await new Promise<string>((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('Desmos image export timed out.')),20000);calc.asyncScreenshot({width:800,height:500,targetPixelRatio:2,format:'png',showLabels:true,mode:'stretch'},(value:string)=>{clearTimeout(timeout);resolve(value);});});return new Uint8Array(await (await fetch(url)).arrayBuffer());}finally{calc?.destroy();el.remove();}}
export function DesmosGraph({diagram}:{diagram:Diagram}){const el=useRef<HTMLDivElement>(null);const [error,setError]=useState('');useEffect(()=>{let cancelled=false,calc:any;setError('');prepare(diagram).then(({Desmos,expressions})=>{if(!cancelled&&el.current)calc=create(el.current,diagram,Desmos,expressions);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;calc?.destroy();};},[diagram]);return <div>{error&&<p role="alert">{error}</p>}<div ref={el} style={{width:'100%',height:400}}/><small>Desmos preview · pan and zoom to explore. Word uses the original graph bounds.</small></div>;}
