import {z} from 'zod';
export const briefSchema=z.object({questionType:z.enum(['MCQ','Structured']).default('Structured'),creativeContext:z.boolean().default(false),multipleParts:z.boolean().default(false),partCount:z.number().int().min(2).max(26).default(2),module:z.literal('EM1'),topic:z.string().max(60),subtopics:z.array(z.string().max(60)).min(1).max(55).refine(ids=>new Set(ids).size===ids.length,'Choose each sub-topic only once.'),totalMarks:z.number().int().min(1).max(Number.MAX_SAFE_INTEGER),difficulty:z.enum(['Basic','Intermediate','Challenging']),specifications:z.string().max(3000).default('')}).transform(b=>b.questionType==='MCQ'?{...b,totalMarks:2,difficulty:'Intermediate' as const,multipleParts:false}:b);
const mark=z.object({part:z.string(),criterion:z.string(),marks:z.number().positive()});
const shape=z.object({type:z.enum(['line','arrow','rect','ellipse','polyline','text']),x:z.number().min(0).max(800),y:z.number().min(0).max(500),x2:z.number().min(0).max(800),y2:z.number().min(0).max(500),width:z.number().min(0).max(800),height:z.number().min(0).max(500),text:z.string().max(150),points:z.array(z.object({x:z.number().min(0).max(800),y:z.number().min(0).max(500)})).max(100),color:z.enum(['#14233b','#174bc7','#15748d','#999999']),fill:z.enum(['none','#ffffff','#dbeafe','#d1f0ed'])});
export const draftSchema=z.object({question_type:z.enum(['MCQ','Structured']),parts:z.array(z.object({label:z.string().min(1).max(10),prompt:z.string().min(3).max(4000)})).max(26),options:z.array(z.object({label:z.enum(['A','B','C','D']),text:z.string().min(1).max(2000)})).max(4),correct_option:z.enum(['A','B','C','D']).nullable(),title:z.string().min(1).max(150),question:z.string().min(10).max(12000),total_marks:z.number().positive(),solutions:z.array(z.object({title:z.string().max(100),content:z.string().min(10).max(16000),marking:z.array(mark).min(1).max(40)})).min(1).max(4),syllabus_ids:z.array(z.string()).min(1).max(55),scope_explanation:z.string().max(2000),difficulty_explanation:z.string().max(2000),diagrams:z.array(z.object({caption:z.string().max(250),placement:z.enum(['question','solution']),shapes:z.array(shape).min(1).max(80)})).max(3)});
export const reviewSchema=z.object({passed:z.boolean(),scope_passed:z.boolean(),format_passed:z.boolean(),issues:z.array(z.string()).max(12),summary:z.string().max(2000)});
export type Brief=z.infer<typeof briefSchema>;export type Draft=z.infer<typeof draftSchema>;
export function jsonSchema(schema:z.ZodType){const result=z.toJSONSchema(schema);delete result.$schema;return result;}

export const feasibilitySchema=z.object({selected_subtopics:z.array(z.string()).min(1).max(55),total_marks:z.number().int().min(1),omitted_subtopics:z.array(z.object({id:z.string(),reason:z.string().min(1).max(1000)})).max(55),marks_reason:z.string().max(2000),specification_adjustments:z.array(z.string().min(1).max(1000)).max(12),resolved_specifications:z.string().max(3000)});
