import katex from 'katex';
import { DOMParser } from '@xmldom/xmldom';
import { zipSync, strToU8, unzipSync, strFromU8 } from 'fflate';
import { mathParts, repairLatex } from './math-text';
import { escapeXML as esc } from './diagram';
import { wordShapes } from './word-shapes';
import type { Draft } from './schema';
import type { Worksheet } from './worksheet';

export type WorksheetContent = Omit<Worksheet, 'sections'> & {
  sections: {
    name: string;
    questions: { result: { draft: Draft }; id: string }[];
  }[];
};
// Reuse the individual exporter so equations and editable diagram shapes keep the same fidelity.
export function worksheetDocument(
  paper: WorksheetContent,
  images: Uint8Array[][],
  lecturer = false,
) {
  const files: Record<string, Uint8Array> = {};
  let rels = '',
    index = 0;
  const questions = paper.sections.flatMap((section) => section.questions);
  const marks = questions.reduce((n, q) => n + q.result.draft.total_marks, 0);
  let body =
    paragraph(paper.title, 'Title') +
    paragraph('Worksheet generated by AI. Review before assessment use.') +
    paragraph(
      `${questions.length} questions · ${marks} marks${lecturer ? ' · Lecturer copy' : ''}`,
    );
  if (paper.includeName)
    body += paragraph('Name: ______________________________');
  if (paper.includeClass)
    body += paragraph('Class: ______________________________');
  if (paper.instructions.trim())
    body +=
      paragraph('Instructions', 'Heading1') + paragraph(paper.instructions);
  const answers: string[] = [];
  for (const section of paper.sections) {
    body += paragraph(section.name, 'Heading1');
    for (const entry of section.questions) {
      const d = entry.result.draft;
      const archive = unzipSync(wordDocument(d, images[index] || []));
      let document = strFromU8(archive['word/document.xml']);
      const prefix = `q${index + 1}_`;
      document = document
        .replace(/r:embed="graph(\d+)"/g, `r:embed="${prefix}graph$1"`)
        .replace(
          /(<wp:docPr id=")(\d+)/g,
          (_, before, id) => before + (index * 100 + Number(id)),
        )
        .replace(
          /(<pic:cNvPr id=")(\d+)/g,
          (_, before, id) => before + (index * 100 + Number(id)),
        );
      document = document.replace(
        /(<wps:cNvPr id=")(\d+)/g,
        (_, before, id) => before + (index * 1000 + Number(id)),
      );
      const imageRels =
        strFromU8(archive['word/_rels/document.xml.rels']).match(
          /<Relationship Id="graph\d+"[^>]+\/>/g,
        ) || [];
      rels += imageRels
        .join('')
        .replace(/Id="graph/g, `Id="${prefix}graph`)
        .replace(/Target="media\//g, `Target="media/${prefix}`);
      for (const [path, data] of Object.entries(archive))
        if (path.startsWith('word/media/'))
          files[path.replace('word/media/', `word/media/${prefix}`)] = data;
      const questionStart = document.indexOf(paragraph('Question', 'Heading1'));
      const solutionStart = document.indexOf(
        paragraph('Main solution', 'Heading1'),
      );
      const end = document.indexOf('<w:sectPr>');
      if (questionStart < 0 || solutionStart < 0 || end < 0)
        throw new Error('Worksheet question could not be assembled.');
      body +=
        paragraph(
          `Question ${index + 1} [${d.total_marks} marks]`,
          'Heading2',
        ) +
        document.slice(
          questionStart + paragraph('Question', 'Heading1').length,
          solutionStart,
        );
      answers.push(
        paragraph(`Question ${index + 1}`, 'Heading2') +
          paragraph(
            d.question_type === 'MCQ'
              ? `${d.correct_option}. ${d.options.find((o) => o.label === d.correct_option)?.text || ''}`
              : d.answer_key || d.solutions[0].content,
          ),
      );
      if (lecturer) body += document.slice(solutionStart, end);
      index++;
    }
  }
  body +=
    '<w:p><w:r><w:br w:type="page"/></w:r></w:p>' +
    paragraph('Answer key', 'Heading1') +
    answers.join('');
  return packageDocument(body, files, rels);
}
const mathRun = (t: string) =>
  `<m:r><m:rPr><m:sty m:val="p"/></m:rPr><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman" w:cs="Times New Roman"/><w:sz w:val="22"/><w:szCs w:val="22"/></w:rPr><m:t xml:space="preserve">${esc(t)}</m:t></m:r>`;
function convert(n: any): string {
  if (n.nodeType === 3) return n.nodeValue.trim() ? mathRun(n.nodeValue) : '';
  if (n.nodeType !== 1) return '';
  const children = Array.from(n.childNodes).filter(
    (c: any) => c.nodeType === 1,
  ) as any[];
  const c = children.map(convert);
  const inside = c.join('');
  switch (n.localName) {
    case 'annotation':
    case 'annotation-xml':
      return '';
    case 'mi':
    case 'mn':
    case 'mo':
    case 'mtext':
      return mathRun(n.textContent);
    case 'mspace':
      return mathRun(' ');
    case 'mfrac':
      return `<m:f><m:num>${c[0]}</m:num><m:den>${c[1]}</m:den></m:f>`;
    case 'msup':
      return `<m:sSup><m:e>${c[0]}</m:e><m:sup>${c[1]}</m:sup></m:sSup>`;
    case 'msub':
      return `<m:sSub><m:e>${c[0]}</m:e><m:sub>${c[1]}</m:sub></m:sSub>`;
    case 'msubsup':
      return `<m:sSubSup><m:e>${c[0]}</m:e><m:sub>${c[1]}</m:sub><m:sup>${c[2]}</m:sup></m:sSubSup>`;
    case 'msqrt':
      return `<m:rad><m:radPr><m:degHide m:val="1"/></m:radPr><m:deg/><m:e>${inside}</m:e></m:rad>`;
    case 'mroot':
      return `<m:rad><m:deg>${c[1]}</m:deg><m:e>${c[0]}</m:e></m:rad>`;
    case 'mover':
      if (['¯', '‾', '―', 'ˉ', '\u0305'].includes(children[1]?.textContent))
        return `<m:bar><m:barPr><m:pos m:val="top"/></m:barPr><m:e>${c[0]}</m:e></m:bar>`;
      return `<m:limUpp><m:e>${c[0]}</m:e><m:lim>${c[1]}</m:lim></m:limUpp>`;
    case 'munder':
      return `<m:limLow><m:e>${c[0]}</m:e><m:lim>${c[1]}</m:lim></m:limLow>`;
    case 'munderover':
      return `<m:limUpp><m:e><m:limLow><m:e>${c[0]}</m:e><m:lim>${c[1]}</m:lim></m:limLow></m:e><m:lim>${c[2]}</m:lim></m:limUpp>`;
    case 'mtable':
      return `<m:m>${inside}</m:m>`;
    case 'mtr':
      return `<m:mr>${inside}</m:mr>`;
    case 'mtd':
      return `<m:e>${inside || mathRun(' ')}</m:e>`;
    case 'menclose':
      return `<m:borderBox><m:e>${inside}</m:e></m:borderBox>`;
    default:
      return inside;
  }
}
export function equation(latex: string) {
  const html = katex.renderToString(repairLatex(latex), {
    output: 'mathml',
    throwOnError: true,
    strict: 'ignore',
  });
  const dom = new DOMParser().parseFromString(html, 'text/xml');
  const math = dom.getElementsByTagName('math')[0];
  if (!math) throw new Error('Equation conversion failed.');
  return `<m:oMath>${convert(math)}</m:oMath>`;
}
function paragraph(text: string, style = '') {
  let pos = 0,
    out = '';
  for (const m of mathParts(text)) {
    if (m.index > pos) out += run(text.slice(pos, m.index));
    out += equation(m.latex);
    pos = m.index + m.raw.length;
  }
  out += run(text.slice(pos));
  return `<w:p><w:pPr>${style ? `<w:pStyle w:val="${style}"/>` : ''}<w:spacing w:after="160"/><w:jc w:val="left"/></w:pPr>${out}</w:p>`;
}
function run(t: string) {
  return t
    .split('\n')
    .map(
      (s, i) =>
        (i ? '<w:r><w:br/></w:r>' : '') +
        `<w:r><w:t xml:space="preserve">${esc(s.replace(/\\\$/g, '$'))}</w:t></w:r>`,
    )
    .join('');
}
export function wordDocument(
  d: Draft,
  images: Uint8Array[],
  refs: string[] = [],
  module = 'Assessment',
) {
  const files: Record<string, Uint8Array> = {};
  let body =
    paragraph(d.title, 'Title') +
    paragraph('Question generated by AI. Review before assessment use.') +
    paragraph(`${module} · ${d.total_marks} marks`) +
    paragraph('Question', 'Heading1') +
    paragraph(d.question) +
    d.parts.map((p) => paragraph(`${p.label} ${p.prompt}`)).join('') +
    d.options.map((o) => paragraph(`${o.label}. ${o.text}`)).join('');
  let rels = '';
  const imageBlock = (i: number) => {
    const diag = d.diagrams[i];
    if (!diag.graph)
      return wordShapes(diag, i + 1, equation) + paragraph(diag.caption);
    if (!images[i]?.length)
      throw new Error('Prepare the Desmos graph image before exporting.');
    files[`word/media/graph${i}.png`] = images[i];
    rels += `<Relationship Id="graph${i}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/graph${i}.png"/>`;
    return (
      `<w:p><w:r><w:drawing><wp:inline><wp:extent cx="5486400" cy="3429000"/><wp:docPr id="${i + 1}" name="Desmos graph" descr="${esc(diag.caption)}"/><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic><pic:nvPicPr><pic:cNvPr id="${i + 1}" name="Desmos graph"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="graph${i}"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="5486400" cy="3429000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>` +
      paragraph(diag.caption)
    );
  };
  d.diagrams.forEach((x, i) => {
    if (x.placement === 'question') body += imageBlock(i);
  });
  d.solutions.forEach((s, i) => {
    body +=
      paragraph(
        i === 0 ? 'Main solution' : `Alternative solution ${i}`,
        'Heading1',
      ) +
      paragraph(s.title) +
      paragraph(s.content);
    if (i === 0)
      d.diagrams.forEach((x, j) => {
        if (x.placement === 'solution') body += imageBlock(j);
      });
    if (d.question_type === 'MCQ')
      body += paragraph(
        `Correct answer: ${d.correct_option}. Award 2 marks for the correct option and 0 otherwise. No partial credit.`,
      );
    else {
      body += paragraph('Proposed marking allocation', 'Heading2');
      s.marking.forEach(
        (m) =>
          (body += paragraph(
            `${m.part ? m.part + ': ' : ''}${m.criterion} [${m.marks} marks]`,
          )),
      );
    }
  });
  if (refs.length)
    body +=
      paragraph('Reference questions', 'Heading2') + paragraph(refs.join('\n'));
  return packageDocument(body, files, rels);
}
function packageDocument(
  body: string,
  files: Record<string, Uint8Array>,
  rels: string,
) {
  const xml = (s: string) =>
    strToU8('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' + s);
  files['word/document.xml'] = xml(
    `<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape"><w:body>${body}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="1134" w:bottom="1134" w:left="1134"/></w:sectPr></w:body></w:document>`,
  );
  files['word/styles.xml'] = xml(
    '<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/><w:sz w:val="22"/></w:rPr></w:rPrDefault></w:docDefaults><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:basedOn w:val="Normal"/><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/><w:b/><w:sz w:val="22"/><w:color w:val="000000"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:pPr><w:keepNext/></w:pPr><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/><w:b/><w:sz w:val="22"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="heading 2"/><w:basedOn w:val="Normal"/><w:pPr><w:keepNext/></w:pPr><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/><w:sz w:val="22"/><w:b/></w:rPr></w:style></w:styles>',
  );
  files['word/settings.xml'] = xml(
    '<w:settings xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"><m:mathPr><m:mathFont m:val="Times New Roman"/></m:mathPr></w:settings>',
  );
  files['word/_rels/document.xml.rels'] = xml(
    `<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="styles" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/><Relationship Id="settings" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings" Target="settings.xml"/>${rels}</Relationships>`,
  );
  files['_rels/.rels'] = xml(
    '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="doc" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>',
  );
  files['[Content_Types].xml'] = xml(
    '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Default Extension="svg" ContentType="image/svg+xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/><Override PartName="/word/settings.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"/></Types>',
  );
  return zipSync(files, { level: 6 });
}
