import assert from 'node:assert/strict';
import {azureURL,anthropicMessages,providerResponse} from '../lib/providers';
assert.equal(azureURL('https://test-resource.openai.azure.com/openai/v1/'),'https://test-resource.openai.azure.com/openai/v1/responses');
for(const u of ['http://test.openai.azure.com','https://evil.test','https://test.openai.azure.com.evil.test','https://test.openai.azure.com:8443','https://user:pass@test.openai.azure.com'])assert.throws(()=>azureURL(u));
const input=[{role:'user',content:[{type:'input_text',text:'reference'},{type:'input_image',image_url:'data:image/png;base64,AAAA'}]},{type:'anthropic_message',_anthropicContent:[{type:'thinking',thinking:'private',signature:'fixture-signature'},{type:'tool_use',id:'a',name:'calculate',input:{expression:'2+2'}}]},{type:'function_call',call_id:'a'},{type:'function_call_output',call_id:'a',output:'4'},{type:'function_call_output',call_id:'b',output:'5'}];
const messages=anthropicMessages(input);assert.equal(messages.length,3);assert.equal(messages[0].content[1].source.type,'base64');assert.equal(messages[1].content[0].signature,'fixture-signature');assert.equal(messages[2].content.length,2);
const original=globalThis.fetch;let calls=0;globalThis.fetch=async(url:any,init:any)=>{calls++;const b=JSON.parse(init.body);if(calls===1){assert.equal(url,'https://api.anthropic.com/v1/messages');assert.equal(init.headers['x-api-key'],'fixture-key');assert.equal(b.model,'claude-sonnet-5');assert.equal(b.output_config.effort,'high');assert.equal(b.thinking.type,'adaptive');assert.equal(b.output_config.format.schema.properties.answer.minLength,undefined);assert(!('store'in b));return Response.json({content:[{type:'tool_use',id:'x',name:'calculate',input:{expression:'2+2'}}]});}assert.equal(url,'https://test-resource.openai.azure.com/openai/v1/responses');assert.equal(init.headers['api-key'],'fixture-key');assert.equal(init.redirect,'manual');assert.equal(b.model,'math-deployment');return Response.json({output:[]});};
const body={instructions:'test',input:[{role:'user',content:[{type:'input_text',text:'test'}]}],text:{format:{schema:{type:'object',properties:{answer:{type:'string',minLength:3}},required:['answer'],additionalProperties:false}}}};
const r=await providerResponse('fixture-key',body,{provider:'anthropic',endpoint:'',deployment:''});assert.equal(r.output[1].type,'function_call');assert.equal(r.output[1].arguments,'{"expression":"2+2"}');await providerResponse('fixture-key',body,{provider:'azure',endpoint:'https://test-resource.openai.azure.com',deployment:'math-deployment'});globalThis.fetch=original;console.log('PASS: Anthropic model, high effort, structured output, images and tool continuity; Azure endpoint restrictions, deployment and authentication. No live credentials used.');

let redirectCalls=0;globalThis.fetch=async()=>{redirectCalls++;return new Response(null,{status:302,headers:{location:'https://elsewhere.example'}})};
await assert.rejects(()=>providerResponse('fixture-key',body,{provider:'openai',endpoint:'',deployment:''}),/redirect/);assert.equal(redirectCalls,1);
globalThis.fetch=async(url:any,init:any)=>{assert.equal(init.redirect,'manual');assert.equal(url,'https://test-resource.openai.azure.com/openai/deployments/course-model/chat/completions?api-version=2024-12-01-preview');const payload=JSON.parse(init.body);assert.equal(payload.reasoning_effort,'high');assert.equal(payload.response_format.type,'json_schema');assert(!payload.response_format.json_schema.type);assert.equal(payload.messages[0].role,'system');return Response.json({choices:[{finish_reason:'stop',message:{role:'assistant',content:'{"ok":true}'}}]});};
const chat=await providerResponse('fixture-key',body,{provider:'azure',endpoint:'https://test-resource.openai.azure.com/',deployment:'course-model',apiVersion:'2024-12-01-preview'});assert.equal(chat.output[1].content[0].text,'{"ok":true}');globalThis.fetch=original;console.log('PASS: edge-compatible redirect rejection and versioned Azure Chat Completions.');
