import assert from 'node:assert/strict';
import fs from 'node:fs';
import { DOMParser, XMLSerializer } from '@xmldom/xmldom';
import { unzipSync, strFromU8 } from 'fflate';
import { wordDocument } from '../lib/word';
import { svgDiagram } from '../lib/diagram';
import { loadPrompts, parsePrompts } from '../lib/prompts';
import {
  addQuestions,
  emptyHistory,
  readHistory,
  updateQuestion,
  selectQuestion,
  resultSchema,
} from '../lib/history';
import { APP_VERSION } from '../lib/version';

const shape = {
  type: 'rect',
  x: 120,
  y: 140,
  x2: 0,
  y2: 0,
  width: 150,
  height: 100,
  text: '',
  points: [],
  color: '#14233b',
  fill: '#dbeafe',
};
const result = resultSchema.parse({
  draft: {
    question_type: 'Structured',
    parts: [],
    options: [],
    correct_option: null,
    title: 'Water diagram export check',
    question:
      'The shaded regions represent water in the containers. Identify each filled region.',
    total_marks: 4,
    solutions: [
      {
        title: 'Solution',
        content: 'The blue and green shaded regions represent water.',
        marking: [
          {
            part: '',
            criterion: 'Identify the four shaded regions.',
            marks: 4,
          },
        ],
      },
    ],
    syllabus_ids: ['EM1-4.4'],
    scope_explanation: 'Export fixture.',
    difficulty_explanation: 'Export fixture.',
    diagrams: [
      {
        caption: 'Filled rectangle, ellipse, polyline and curved region',
        placement: 'question',
        graph: null,
        shapes: [
          shape,
          { ...shape, type: 'ellipse', x: 450, y: 190, fill: '#d1f0ed' },
          {
            ...shape,
            type: 'polyline',
            points: [
              { x: 150, y: 300 },
              { x: 300, y: 300 },
              { x: 225, y: 440 },
            ],
          },
          {
            ...shape,
            type: 'curve',
            fill: '#d1f0ed',
            points: [
              { x: 400, y: 300 },
              { x: 450, y: 430 },
              { x: 550, y: 430 },
              { x: 600, y: 300 },
            ],
          },
          {
            ...shape,
            type: 'line',
            x: 100,
            y: 80,
            x2: 650,
            y2: 80,
            fill: 'none',
          },
        ],
      },
    ],
  },
  references: [],
  review: { passed: true, issues: [], summary: 'Fixture review.' },
  calculations: [],
  exactExamples: 0,
  brief: {
    module: 'EM1',
    topic: 'EM1-4',
    subtopics: ['EM1-4.4'],
    totalMarks: 4,
    difficulty: 'Basic',
  },
  effectiveBrief: {
    module: 'EM1',
    topic: 'EM1-4',
    subtopics: ['EM1-4.4'],
    totalMarks: 4,
    difficulty: 'Basic',
  },
  feasibility: {
    selected_subtopics: ['EM1-4.4'],
    total_marks: 4,
    omitted_subtopics: [],
    marks_reason: '',
    specification_adjustments: [],
    resolved_specifications: '',
  },
});
const document = wordDocument(result.draft, []);
fs.mkdirSync('test-output', { recursive: true });
fs.writeFileSync('test-output/filled-shapes.docx', document);
fs.writeFileSync('test-output/history-fixture.json', JSON.stringify(result));
fs.writeFileSync(
  'test-output/filled-shapes.svg',
  svgDiagram(result.draft.diagrams[0]),
);
const xml = strFromU8(unzipSync(document)['word/document.xml']);
const dom = new DOMParser().parseFromString(xml, 'text/xml');
const shapes = Array.from(dom.getElementsByTagName('wps:wsp'));
assert.equal(shapes.length, 5);
for (const [i, color] of ['dbeafe', 'd1f0ed', 'dbeafe', 'd1f0ed'].entries()) {
  assert(
    new XMLSerializer().serializeToString(shapes[i]).includes(`val="${color}"`),
  );
}
assert.equal(
  shapes[2].getElementsByTagName('a:path')[0].getAttribute('fill'),
  'norm',
);
assert.equal(
  shapes[3].getElementsByTagName('a:path')[0].getAttribute('fill'),
  'norm',
);
assert.equal(
  shapes[4].getElementsByTagName('a:path')[0].getAttribute('fill'),
  'none',
);
assert(xml.includes('Question generated by AI. Review before assessment use.'));
assert(
  xml.indexOf('Question generated by AI.') < xml.indexOf(result.draft.question),
);
assert(!xml.includes('<pic:pic>'));
const unfilled = structuredClone(result.draft);
unfilled.diagrams[0].shapes.forEach((s) => (s.fill = 'none'));
assert(
  !strFromU8(
    unzipSync(wordDocument(unfilled, []))['word/document.xml'],
  ).includes('fill="norm"'),
);

let history = addQuestions(emptyHistory(), [result]);
const firstId = history.activeId!;
history = addQuestions(history, [result, result, result]);
assert.equal(
  history.batches.reduce((n, b) => n + b.results.length, 0),
  4,
);
history = selectQuestion(history, firstId, 0);
const updated = {
  ...result,
  manual: true,
  draft: { ...result.draft, title: 'Refined water question' },
};
history = updateQuestion(history, updated);
const restored = readHistory(JSON.stringify(history));
assert.equal(restored.sessionId, history.sessionId);
assert.equal(restored.activeId, firstId);
assert.equal(restored.batches.length, 2);
assert.equal(
  restored.batches[0].results[0].draft.title,
  'Refined water question',
);
assert.equal(restored.batches[0].results[0].manual, true);
assert.equal(restored.batches[1].results[0].draft.title, result.draft.title);
assert.throws(() => readHistory('broken json'));
assert.throws(() =>
  readHistory(JSON.stringify({ ...history, candidateIndex: 2 })),
);
assert.throws(() => readHistory(JSON.stringify({ ...history, version: 2 })));
const prompts = loadPrompts();
assert.match(
  prompts.version,
  /^EM1@\d{4}-\d{2}-\d{2}\+shared@\d{4}-\d{2}-\d{2}$/,
);
assert(prompts.text.author.includes('\\[...\\]'));
assert(prompts.text.author.includes('2x\\,\\mathrm{cm}'));
const source = fs.readFileSync('PROMPTS.md', 'utf8');
assert.throws(() =>
  parsePrompts(source.replace(/^## author\r?$/m, '## missing')),
);
assert.throws(() =>
  parsePrompts(source + '\n## author\n```text\nDuplicate\n```\n'),
);
assert.throws(() =>
  parsePrompts(
    source.replace(`Version: ${prompts.sharedVersion}`, 'Version: 2026-02-30'),
  ),
);
assert.notEqual(
  parsePrompts(source.replace('You author module', 'You create module')).hash,
  parsePrompts(source).hash,
);
for (const path of ['README.md', 'DOCUMENTATION.md'])
  assert(fs.readFileSync(path, 'utf8').includes(`Version: ${APP_VERSION}`));
console.log(
  'PASS: editable filled geometry and visible AI notice; session history restore/refinement/count; live prompt configuration and release dates.',
);
